"""Monitoring Query Layer and Service for FORGE AI Pipeline."""

import json
import logging
from pathlib import Path
from typing import Optional, List, Dict, Any, Union

from backend.monitoring.execution_event import ExecutionEvent, EventType

logger = logging.getLogger("monitoring_service")


class MonitoringService:
    """Reusable monitoring & query service operating on structured ExecutionEvents."""

    def __init__(
        self,
        logger_instance: Optional[Any] = None,
        log_filepath: Optional[Union[str, Path]] = None,
        log_dir: Optional[Union[str, Path]] = None,
    ):
        self.logger_instance = logger_instance
        if log_filepath:
            self.log_filepath = Path(log_filepath)
        elif log_dir:
            self.log_filepath = Path(log_dir) / "pipeline_execution.jsonl"
        elif logger_instance and hasattr(logger_instance, "log_filepath"):
            self.log_filepath = Path(logger_instance.log_filepath)
        else:
            self.log_filepath = Path("backend/data/logs/pipeline_execution.jsonl")

    def get_all_events(self) -> List[ExecutionEvent]:
        """Fetch all execution events combining memory buffer and persistent storage."""
        events: List[ExecutionEvent] = []
        seen_ids = set()

        # 1. Read persistent JSONL file records
        if self.log_filepath.exists():
            try:
                with open(self.log_filepath, "r", encoding="utf-8") as f:
                    for line in f:
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            data = json.loads(line)
                            evt = ExecutionEvent.model_validate(data)
                            if evt.event_id not in seen_ids:
                                events.append(evt)
                                seen_ids.add(evt.event_id)
                        except Exception as parse_err:
                            logger.error(f"Failed parsing log record: {parse_err}")
            except Exception as read_err:
                logger.error(f"Failed reading log file {self.log_filepath}: {read_err}")

        # 2. Include in-memory logger events if present
        if self.logger_instance and hasattr(self.logger_instance, "get_events"):
            for evt in self.logger_instance.get_events():
                if evt.event_id not in seen_ids:
                    events.append(evt)
                    seen_ids.add(evt.event_id)

        return events

    def get_events_by_run_id(self, run_id: str) -> List[ExecutionEvent]:
        """Retrieve all events associated with a specific run_id."""
        return [evt for evt in self.get_all_events() if evt.run_id == run_id]

    def get_events_by_project_id(self, project_id: str) -> List[ExecutionEvent]:
        """Retrieve all events associated with a specific project_id."""
        return [evt for evt in self.get_all_events() if evt.project_id == project_id]

    def get_events_by_agent(
        self, agent_name: str, run_id: Optional[str] = None
    ) -> List[ExecutionEvent]:
        """Retrieve all events generated by a specific agent."""
        events = self.get_events_by_run_id(run_id) if run_id else self.get_all_events()
        return [evt for evt in events if evt.agent_name == agent_name]

    def get_failed_events(
        self, run_id: Optional[str] = None, project_id: Optional[str] = None
    ) -> List[ExecutionEvent]:
        """Retrieve failed events (AGENT_FAILED, PIPELINE_FAILED, ARTIFACT_FAILED)."""
        events = self.get_all_events()
        if run_id:
            events = [e for e in events if e.run_id == run_id]
        if project_id:
            events = [e for e in events if e.project_id == project_id]

        fail_types = {
            EventType.AGENT_FAILED,
            EventType.PIPELINE_FAILED,
            EventType.ARTIFACT_FAILED,
        }
        return [evt for evt in events if evt.event_type in fail_types or evt.status == "FAILED"]

    def get_events_by_stage(
        self, pipeline_stage: str, run_id: Optional[str] = None
    ) -> List[ExecutionEvent]:
        """Retrieve all events for a given pipeline stage."""
        events = self.get_events_by_run_id(run_id) if run_id else self.get_all_events()
        return [evt for evt in events if evt.pipeline_stage == pipeline_stage]

    def get_execution_metrics(
        self, run_id: Optional[str] = None, project_id: Optional[str] = None
    ) -> Dict[str, Any]:
        """Calculate execution metrics for a specific run or project (or all events)."""
        events = self.get_all_events()
        if run_id:
            events = [e for e in events if e.run_id == run_id]
        if project_id:
            events = [e for e in events if e.project_id == project_id]

        if not events:
            return {
                "total_pipeline_duration_ms": 0.0,
                "per_agent_duration_ms": {},
                "successful_agent_count": 0,
                "failed_agent_count": 0,
                "total_artifacts_created": 0,
                "artifact_count": 0,
                "failed_artifacts": 0,
                "failed_artifact_count": 0,
                "pipeline_status": "PENDING",
                "agent_statuses": {},
                "latest_event_type": None,
                "latest_event_timestamp": None,
            }

        per_agent_duration_ms: Dict[str, float] = {}
        agent_statuses: Dict[str, str] = {}
        successful_agents = set()
        failed_agents = set()
        artifacts_created = 0
        failed_artifacts = 0
        total_duration_ms = 0.0
        pipeline_status = "RUNNING"

        for evt in events:
            if evt.agent_name and evt.duration_ms is not None:
                per_agent_duration_ms[evt.agent_name] = evt.duration_ms

            if evt.event_type == EventType.AGENT_COMPLETED and evt.agent_name:
                successful_agents.add(evt.agent_name)
                agent_statuses[evt.agent_name] = "COMPLETED"
            elif evt.event_type == EventType.AGENT_FAILED and evt.agent_name:
                failed_agents.add(evt.agent_name)
                agent_statuses[evt.agent_name] = "FAILED"
            elif evt.event_type == EventType.AGENT_STARTED and evt.agent_name:
                if evt.agent_name not in agent_statuses:
                    agent_statuses[evt.agent_name] = "RUNNING"

            if evt.event_type == EventType.ARTIFACT_CREATED:
                artifacts_created += 1
            elif evt.event_type == EventType.ARTIFACT_FAILED:
                failed_artifacts += 1

            if evt.event_type == EventType.PIPELINE_COMPLETED:
                pipeline_status = "COMPLETED"
                if evt.duration_ms is not None:
                    total_duration_ms = evt.duration_ms
            elif evt.event_type == EventType.PIPELINE_FAILED:
                pipeline_status = "FAILED"
                if evt.duration_ms is not None:
                    total_duration_ms = evt.duration_ms

        if total_duration_ms == 0.0 and per_agent_duration_ms:
            total_duration_ms = round(sum(per_agent_duration_ms.values()), 2)

        latest_event = events[-1]

        return {
            "total_pipeline_duration_ms": total_duration_ms,
            "per_agent_duration_ms": per_agent_duration_ms,
            "successful_agent_count": len(successful_agents),
            "failed_agent_count": len(failed_agents),
            "total_artifacts_created": artifacts_created,
            "artifact_count": artifacts_created,
            "failed_artifacts": failed_artifacts,
            "failed_artifact_count": failed_artifacts,
            "pipeline_status": pipeline_status,
            "agent_statuses": agent_statuses,
            "latest_event_type": latest_event.event_type.value,
            "latest_event_timestamp": latest_event.timestamp,
        }
