"""Pydantic V2 schemas for PM Agent Output validation."""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class EntityField(BaseModel):
    """Field definition in a database entity."""
    name: str = Field(..., description="Field name")
    type: str = Field(..., description="Field data type (e.g. INTEGER, VARCHAR, DATETIME)")
    nullable: Optional[bool] = Field(default=True, description="Whether field can be NULL")
    primary_key: Optional[bool] = Field(default=False, description="Whether field is primary key")
    unique: Optional[bool] = Field(default=False, description="Whether field is unique")
    description: Optional[str] = Field(default=None, description="Field description")


class DatabaseEntity(BaseModel):
    """Database entity generated by PM agent."""
    name: str = Field(..., description="Entity name e.g. User, Task")
    description: Optional[str] = Field(default=None, description="Entity description")
    fields: List[EntityField] = Field(default_factory=list, description="Fields belonging to entity")


class TechStack(BaseModel):
    """Tech stack choice."""
    frontend: Optional[str] = Field(default="React", description="Frontend framework")
    backend: Optional[str] = Field(default="FastAPI", description="Backend framework")
    database: Optional[str] = Field(default="PostgreSQL", description="Database system")


class PMOutput(BaseModel):
    """PM Agent JSON output schema."""
    project_name: str = Field(..., description="Project name")
    description: str = Field(..., description="Project summary description")
    features: List[str] = Field(default_factory=list, description="Core feature list")
    tech_stack: Optional[TechStack] = Field(default_factory=TechStack, description="Target tech stack")
    database_entities: List[DatabaseEntity] = Field(default_factory=list, description="Extracted database entities")
